# Common configurations

imageCredentials:
  password: ""

domain: ""
license: ""
superusers: ""
mongo:
  url: ""
redis:
  url: ""
stage: "enterprise"
ssl:
  generator: ""

# Kubernetes Ingress configuration
ingress:
  class: ""
  annotations: {}

# Persistent Volume Storage
storage:
  size: "50Gi"
  # you can either use a storage class
  class: "nfs"
  # or configure your own NFS server
  server: ""
  path: ""

# API configurations
api:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  podAnnotations: {}

  service:
    type: ""


# Frontend configurations
frontend:
  replicas: 1
  cpu: ""
  memory: ""

  service:
    type: ""


# Proxy configurations
proxy:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  podAnnotations: {}

  service:
    type: ""


# Recording configurations
recording:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  podAnnotations: {}

  service:
    type: ""


# Sockets configurations
sockets:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  podAnnotations: {}

  service:
    type: ""
