# Common configurations

imageCredentials:
  password: ""

domain: ""
license: ""

superusers: ""
mongo:
  url: "mongodb://mongodb.cobrowse.svc.cluster.local:27017/cobrowse-io"
redis:
  url: "redis://redis-redis-cluster.cobrowse.svc.cluster.local"
stage: "enterprise"
ssl:
  generator: ""

# Kubernetes Ingress configuration
ingress:
  class: "nginx"
  annotations: {}

# Persistent Volume Storage
storage:
  size: "50Gi"
  # you can either use a storage class
  class: ""
  # or configure your own NFS server
  server: ""
  path: ""

# Image configurations

# API configurations
api:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""

# Frontend configurations
frontend:
  replicas: 1
  cpu: ""
  memory: ""

  service:
    type: ""

# Proxy configurations
proxy:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""

# Recording configurations
recording:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""

# Sockets configurations
sockets:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""
